## Dovecot configuration for sandflow.club
## See /usr/share/doc/dovecot-core/dovecot/ for full documentation.

# Protocols to serve
protocols = imap pop3 lmtp

# Listen on all interfaces
listen = *

# Base directory
base_dir = /var/run/dovecot/

# Enabled mail plugins
mail_plugins = quota

# Include modular configuration files
!include conf.d/*.conf
!include_try /usr/share/dovecot/protocols.d/*.protocol
