##
## Mailbox locations and namespaces
##

# Mail location: Maildir in user home directory
mail_location = maildir:~/Maildir

# Namespace for private inbox
namespace inbox {
  inbox = yes

  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Trash {
    special_use = \Trash
  }
  mailbox Sent {
    special_use = \Sent
  }
}
