##
## SSL settings
##

# Require SSL/TLS
ssl = required

# Let's Encrypt certificate
ssl_cert = </etc/letsencrypt/live/smtp.sandflow.club/fullchain.pem
ssl_key = </etc/letsencrypt/live/smtp.sandflow.club/privkey.pem

# Minimum TLS protocol
ssl_min_protocol = TLSv1.2

# Prefer server cipher order
ssl_prefer_server_ciphers = yes

# DH parameters length
ssl_dh = </usr/share/dovecot/dh.pem
